hawai.projectName=posdoc
hawai.applicationName=posdoc
hawai.targetDir=./dist/
hawai.applicationBinFileName=posdoc_fe_ihm.tar.gz
hawai.hawaiVersion=hawai6
hawai.fedex=false
hawai.onlyUpdateProjectVersionLastDigit=true
hawai.updateApplicationVersion=false
