sonar.projectKey=POSDOC_posdoc-ihm-fe
sonar.projectVersion=1.0
sonar.projectName=posdoc-ihm-fe
sonar.sources=src/app
sonar.exclusions=**/node_modules/**, **/karma.dev.conf.js, **/karma.conf.js
sonar.test.inclusions=src/**/*.spec.ts
sonar.ts.tslint.configPath=tslint.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.junit.reportPaths=reports/test-report.xml
sonar.testExecutionReportPaths=reports/sonarqube_report.xml
sonar.language=ts
sonar.tests=src
sonar.coverage.exclusions=**/api-*.service.ts, **/api-adelaide-version-service.ts, **/service-api-reedition-massification.service.ts, **/fullstack-components/**/*.*
