<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>posdoc-ihm-be</artifactId>
        <groupId>fr.acoss.posdoc</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>posdoc-ihm-be-flyway</artifactId>

    <properties>
        <java.version>11</java.version>

        <!-- On force la base de test e2e -->
        <flyway.url>jdbc:postgresql://10.207.89.197:5432/posdoc_e2e</flyway.url>
        <flyway.user>user_e2e</flyway.user>
        <flyway.password>pg_posdoc?</flyway.password>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>9.22.3</version>
                <configuration>
                    <url>${flyway.url}</url>
                    <user>${flyway.user}</user>
                    <password>${flyway.password}</password>

                    <cleanDisabled>false</cleanDisabled>
                    <mixed>true</mixed>
                    <validateMigrationNaming>true</validateMigrationNaming>
                    <schemas>
                        <schema>public</schema>
                        <schema>cereus</schema>
                        <schema>posdoc</schema>
                    </schemas>
                    <locations>
                        <location>filesystem:src/main/resources/db/migration</location>
                        <location>filesystem:src/main/resources/db/callback</location>
                    </locations>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.7.3</version>
                    </dependency>
                </dependencies>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>fr.acoss.posdoc.flyway.FlywayCleaner</mainClass>
                    <arguments>
                        <argument>${project.basedir}</argument>
                    </arguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>