schema: 'src/main/resources/graphql/**/*.graphqls'
documents: 'src/main/resources/graphql/**/*.graphqls'
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:8080/graphql
      headers:
        user-agent: JS GraphQL
        Authorization: Bearer eyJhbGciOiJSUzUxMiIsImtpZCI6InVFblJQMy1ycjUwYU9fdnhYUDR0RVB2YjJfeWZuTHZrTUZUU0V3R2ZoZHMifQ.eyJleHAiOjE2MDUyOTg2NjIsInN1YiI6IkFDNzUwVDkwMTFAY249VVNSX1JFQURfTkFUX0FQUF9QT1NET0MtQkUsb3U9UE9TRE9DLUJFLG91PUFwcGxpY2F0aW9ucyxvdT1UZWNobmlxdWUsZGM9cmVjb3V2IiwiYXVkIjoiSDRzSUFBQUFBQUFBQUhOeGRYTU05UW14Q3ZBUGR2RjMxblZ5dFhKMGRuWU5qbmQwOGZYMDh3d09DWElNOGZUM0F3REphUHkySmdBQUFBPT0iLCJpc3MiOiJodHRwczpcL1wvZ2F0ZXdheS51cnNzYWYucmVjb3V2IiwiaWRfc3RvcmUiOiJINHNJQUFBQUFBQUFBSE4wTmpjMUNMRTBNRFMwU3M2ekRRME9pZzl5ZFhTSjkzTU1pWGNNQ0lnUDhBOTI4WGZXZFhMVnlTKzFSZUU0RmhUa1pDWW5sbVRtNXhXRCtDR3B5Umw1bVlXbHFUb3B5YlpGcWNuNXBXV0swUjRteFo2T01PRG5YK2xjNWhpUVV1Wm1iSmdYVnVrVTZPVGxYZUVTNGx3T2tyUzFqUVVBVlJ3aktZc0FBQUE9IiwianRpIjoiZmExOTY5Mzg0ODZjMTdlMzYxYjRlNmEwMmI5ZWYzMTQiLCJpYXQiOjE1NzM2NDAyNjJ9.GMJs4bcU0qICdO1LEtRgEpuAiyDvhEcb0l3Ihf8dqG2GAvGSaTkFJKWNYYFp5YsQhEpw3zhzDxETtPpdgHMtut_vPBzYOm50XP3DQs4USUEkWzu9saj4WGu1RNnpfr2aWVrqrY-s-ZoLO54LHP2XT-RSiK38lruQFDtR7dtWt3o
      introspect: false
