<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>posdoc-ihm-be</artifactId>
        <groupId>fr.acoss.posdoc</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>posdoc-ihm-be-ws</artifactId>
    <packaging>war</packaging>

    <properties>
        <graphql-spring-boot-starter.version>7.1.0</graphql-spring-boot-starter.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>fr.acoss.posdoc</groupId>
            <artifactId>posdoc-ihm-be-commons</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>fr.acoss.posdoc</groupId>
            <artifactId>posdoc-ihm-be-security</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>fr.acoss.posdoc</groupId>
            <artifactId>posdoc-ihm-be-database</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>fr.acoss.posdoc</groupId>
            <artifactId>posdoc-ihm-be-domain</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>

            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>${graphql-spring-boot-starter.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- iText7 for PDF generation -->
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itext7-core</artifactId>
            <version>7.2.5</version>
            <type>pom</type>
        </dependency>

        <!-- PDFBox for PDF printing -->
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>2.0.27</version>
        </dependency>

        <!-- to embed GraphiQL tool -->
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphiql-spring-boot-starter</artifactId>
            <version>${graphql-spring-boot-starter.version}</version>
            <scope>runtime</scope>
        </dependency>

        <!-- TESTS -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter-test</artifactId>
            <version>${graphql-spring-boot-starter.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- SOAP Dependencies for Anais Web Service -->
        <dependency>
            <groupId>com.sun.xml.messaging.saaj</groupId>
            <artifactId>saaj-impl</artifactId>
            <version>1.5.3</version>
        </dependency>

        <dependency>
            <groupId>javax.xml.soap</groupId>
            <artifactId>javax.xml.soap-api</artifactId>
            <version>1.4.0</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>posdoc_be_ihm</finalName>
        <plugins>
            
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <!-- Permet de livrer sur la plateforme hawai -->
            <!--dépot : http://svn.hawai.recouv/apps-v6/hwi_postdoc/trunk -->
            <plugin>
                <groupId>fr.acoss.industrialisation.maven</groupId>
                <artifactId>hawai-maven-plugin</artifactId>
                <version>${hawai-maven-plugin.version}</version>
                <configuration>
                    <!-- Nom du projet dans le repo hawai : posdoc => /apps-v6/hwi_posdoc -->
                    <projectName>posdoc</projectName>
                    <applicationBinFileName>${project.build.finalName}.war</applicationBinFileName>
                    <hawaiVersion>hawai6</hawaiVersion>
                    <fedex>false</fedex>
                    <updateApplicationVersion>false</updateApplicationVersion>
                    <onlyUpdateProjectVersionLastDigit>true</onlyUpdateProjectVersionLastDigit>
                    <!--                    production de document untitaire inexistant sur la branche lot_6.0_cereus pour le moment-->
                    <branchName>${branche.hawai}</branchName>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                        <configuration>
                            <includeCurrentProject>true</includeCurrentProject>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>com.internetitem</groupId>
                <artifactId>write-properties-file-maven-plugin</artifactId>
                <version>2.0.0</version>
                <executions>
                    <execution>
                        <id>version-properties</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>write-properties-file</goal>
                        </goals>
                        <configuration>
                            <filename>version.properties</filename>
                            <properties>
                                <property>
                                    <name>date</name>
                                    <value>${maven.build.timestamp}</value>
                                </property>
                                <property>
                                    <name>version</name>
                                    <value>${project.version}</value>
                                </property>
                            </properties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>


</project>