query Query  ($page: Int!, $size: Int!, $sort:[SortInput]!, $criteria: [FilterCriterionInput]!) {
    tarifs : tarifs(queryParameters: {
        paginationParameters: {
            page: $page
            size: $size
            sort: $sort
        }
        filterCriteria: {
            criteria: $criteria
        }

    }) {
        totalElement
        totalPages
        elements {
            ... on Tarif {
                type
                numero
                dateDebut
                dateFin
                coutPli
                remise1
                remise2
                remise3
                urgent
            }
        }
    }
}