INSERT INTO Region (C62_Codreg, S62_Libreg) VALUES
    ('R01', 'REGION SANS ORGANISME'),
    ('R02', 'REGION AVEC UN ORGANISME'),
    ('R03', 'REGION AVEC MULTI ORGANISMES'),
    ('R04', 'AUTRE REGION SANS ORGANISME');

INSERT INTO ORGANI (C00_Codorg, S00_Liborg, S00_Adres1, S00_Adres2, S00_Adres3, S00_Adres4, S00_Typorg, S00_Codreg, S00_Codsit) VALUES
    ('100', 'ORGANISME LIE R02',    NULL, NULL, NULL, NULL, 'R', 'R02', ''),
    ('210', 'ORGANISME LIE R03 #1', NULL, NULL, NULL, NULL, 'R', 'R03', ''),
    ('220', 'ORGANISME LIE R03 #2', NULL, NULL, NULL, NULL, 'R', 'R03', ''),
    ('230', 'ORGANISME LIE R03 #3', NULL, NULL, NULL, NULL, 'R', 'R03', ''),
    ('999', 'ORGANISME ORPHELIN',   NULL, NULL, NULL, NULL, 'R', 'R99', '');
