query searchPliByNumpli($id: String) {
    searchPliByNumpli(numpli: $id) {
        numpli
        codenv
        codorg
        codapp
        percod
        codcom
        codfic
        numcom
        plista
        pliinf
        zoncli
        dplidc
        dplidd
        dplidt
        dplide
        dplidh
        nbpage
        nbfeui
        edtype
        poipli
        coupli
        idtpli
        codpos
        codpay
        adres1
        adres2
        adres3
        adres4
        adres5
        adres6
        expad1
        expad2
        expad3
        expad4
        genpro
        infcl1
        infcl2
        datdep
        mpsidd
        status
        cominf
        codgam
        prosta
        proinf
        prefec
        dprodc
        dprodd
        dprodt
        dprods
        dprodh
        pagfic
        plific
        rejfic
    }
}