query Query  ($page: Int!, $size: Int!, $sort:[SortInput]!, $criteria: [FilterCriterionInput]!) {
    parametresDistribution : parametresDistribution(queryParameters: {
        paginationParameters: {
            page: $page
            size: $size
            sort: $sort
        }
        filterCriteria: {
            criteria: $criteria
        }

    }) {
        totalElement
        totalPages
        elements {
            ... on ParametreDistribution{
                reference
                libelle
                commandeDistribution
                logicielDistribution
            }
        }
    }
}