query Query  ($page: Int!, $size: Int!, $sort:[SortInput]!, $criteria: [FilterCriterionInput]!) {
    parametres : parametres(queryParameters: {
        paginationParameters: {
            page: $page
            size: $size
            sort: $sort
        }
        filterCriteria: {
            criteria: $criteria
        }

    }) {
        totalElement
        totalPages
        elements {
            ... on Parametre{
                code
                libelle
                value
            }
        }
    }
}